---
language: ruby
sudo: false
cache: bundler
notifications:
  email:
    on_failure: always
branches:
  only:
    - master
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
